import Head from "next/head";
import Image from "next/image";
import { ConnectButton } from "@rainbow-me/rainbowkit";
import { useAccount, useProvider } from "wagmi";
import styles from "../styles/Home.module.css";

const Home = () => {
  // const provider = useProvider();
  const account = useAccount();

  return (
    <div className={styles.container}>
      <Head>
        <title>NFT Market DApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ConnectButton />
      <div>
        {account.isConnected && `Account: ${account.address} connected`}
      </div>
    </div>
  );
};

export default Home;
